spring:
  datasource:
    url: jdbc:mysql://badlook2.mysql.rds.aliyuncs.com:3306/micro-account
#    url: jdbc:mysql://rdsvebirzvebirzo.mysql.rds.aliyuncs.com:3306/micro-mvs
    username: MicroAccount
    password: MicroAccount@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  path: /usr/local/himedia-account
  level:
    root: INFO