spring:
  datasource:
    url: jdbc:mysql://172.20.6.110:3306/springcloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  context-path: /uaa
  port: 11002

#add
security:
  sessions: if-required
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      authorized-grant-types: authorization_code,refresh_token,password,client_credentials
      scope: openid