server:
  context-path: /hmd-box
  port: 11009

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: hmd_123456
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 1000
      min-idle: 0
    timeout: 0


logging:
  path:  /Users/pg/Downloads/
  level:
    root: INFO