server:
  context-path: /mvs-consumer
  port: 11008

spring:
  redis:
    database: 0
    host: 112.124.96.140
    port: 6379
    password: himedia@123
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 1000
      min-idle: 0
    timeout: 0

logging:
  path:  /Users/pg/Downloads/
  level:
    root: INFO