server:
  context-path: /test-micro-client
  port: 6022

spring:
  redis:
    database: 0
    host: 172.20.6.110
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 10000
      max-idle: 1000
      min-idle: 0
    timeout: 0

logging:
  path: /springboot/logs/test-micro-client
  level:
    root: INFO